# Generated by Django 5.2.8 on 2025-11-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestoCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99)),
                ('description', models.TextField()),
                ('price', models.IntegerField(max_length=8)),
                ('imgurl', models.TextField()),
            ],
        ),
    ]
