# Generated by Django 5.2.8 on 2025-11-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restocard',
            old_name='imgurl',
            new_name='imgUrl',
        ),
        migrations.RemoveField(
            model_name='restocard',
            name='price',
        ),
    ]
