# Generated by Django 5.2.8 on 2025-11-12 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_imgurl_restocard_imgurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restocard',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2025, 11, 12)),
        ),
    ]
