# Generated by Django 5.2.8 on 2025-11-12 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_restocard_price_alter_restocard_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restocard',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2025, 11, 13)),
        ),
        migrations.AlterField(
            model_name='restocard',
            name='imgUrl',
            field=models.ImageField(upload_to='menu'),
        ),
    ]
