# Generated by Django 5.2.8 on 2025-11-27 02:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_restocard_created_at_alter_restocard_imgurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restocard',
            name='imgUrl',
        ),
        migrations.AlterField(
            model_name='restocard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='restocard',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='food_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.restocard')),
            ],
        ),
    ]
